// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfEPggH24wqi8IOTbzpM7j1ZbmO_1l1Ho',
    appId: '1:27319422735:web:312762bd4b59121d71787a',
    messagingSenderId: '27319422735',
    projectId: 'photoframe-f5ca0',
    authDomain: 'photoframe-f5ca0.firebaseapp.com',
    storageBucket: 'photoframe-f5ca0.firebasestorage.app',
    measurementId: 'G-ERCRRHRTPT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRgWLayP3tbsMx7HL8_tjLgzDdLQC5F4U',
    appId: '1:27319422735:android:68d6bc0c39858e4371787a',
    messagingSenderId: '27319422735',
    projectId: 'photoframe-f5ca0',
    storageBucket: 'photoframe-f5ca0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrRo2AO3ImKvlXLDpODXzpH2vB8w8VdbM',
    appId: '1:27319422735:ios:8a0c58dd661b2ea671787a',
    messagingSenderId: '27319422735',
    projectId: 'photoframe-f5ca0',
    storageBucket: 'photoframe-f5ca0.firebasestorage.app',
    iosBundleId: 'com.example.photoframe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrRo2AO3ImKvlXLDpODXzpH2vB8w8VdbM',
    appId: '1:27319422735:ios:8a0c58dd661b2ea671787a',
    messagingSenderId: '27319422735',
    projectId: 'photoframe-f5ca0',
    storageBucket: 'photoframe-f5ca0.firebasestorage.app',
    iosBundleId: 'com.example.photoframe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfEPggH24wqi8IOTbzpM7j1ZbmO_1l1Ho',
    appId: '1:27319422735:web:8d740e2cd94374f071787a',
    messagingSenderId: '27319422735',
    projectId: 'photoframe-f5ca0',
    authDomain: 'photoframe-f5ca0.firebaseapp.com',
    storageBucket: 'photoframe-f5ca0.firebasestorage.app',
    measurementId: 'G-3YCD6P46ZC',
  );

}